name: CI
on:
  push:
  pull_request:
jobs:
  shellcheck:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shellcheck
        run: brew install shellcheck
      - name: Run shellcheck
        run: shellcheck --color=always mailsecchk.sh
