name: CI
on:
  push:
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Run shellcheck
        run: shellcheck --color=always mailsecchk.sh
